#!/bin/bash 

RgName="idempiere-rg"
Location="eastus" 

# Create a resource group.
az group create \
--name $RgName \
--location $Location 

# Create a virtual network with a front-end subnet. 
az network vnet create \
--name MyVnet \
--resource-group $RgName \
--location $Location \
--address-prefix 10.0.0.0/16 \
--subnet-name MySubnet-FrontEnd \
--subnet-prefix 10.0.1.0/24


# Create a back-end subnet.

az network vnet subnet create \
--address-prefix 10.0.2.0/24 \
--name MySubnet-BackEnd \
--resource-group $RgName \
--vnet-name MyVnet

#create VM Backend

az vm create \
--resource-group $RgName \
--name serverBackEnd \
--location $Location \
--vnet-name MyVNet \
--subnet MySubnet-BackEnd \
--image Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest \
--admin-username azureuser \
--generate-ssh-keys 


#create VM FrontEnd

az vm create \
--resource-group $RgName \
--name FrontEnd \
--location $Location \
--vnet-name MyVNet \
--subnet MySubnet-FrontEnd \
--image Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest \
--admin-username azureuser \
--generate-ssh-keys

# after connect ServerBackEnd via SSH - Create the file repository configuration:
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
# Import the repository signing key:
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
# Update the package lists:
sudo apt-get update
# Install the version 13 of PostgreSQL.
sudo apt-get -y install postgresql-13

echo "alter user postgres password 'idempierepostgres'" | sudo su postgres -c "psql -U postgres"

sudo service postgresql reload


# after connecting front end Create the file repository configuration:
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
# Import the repository signing key:
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
# Update the package lists:
sudo apt-get update
